services:
  backend:
    restart: "no"
    command:
      npx tsx watch src/server.ts
    develop:
      watch:
        - action: rebuild
          path: ./sharedLib/src
        - action: rebuild
          path: ./sharedLib/package.json
        - action: rebuild
          path: ./server/package.json
        - action: sync
          path: ./server/src
          target: /app/server/src
          
    build:
      context: ./
      dockerfile: server/Dockerfile.dev