# Builds and uploads artifacts for client

name: Build Client App

on:
  workflow_dispatch:
  push:
    tags: ["v[0-9]+.[0-9]+", "v[0-9]+.[0-9]+.[0-9]+", "v[0-9]+.[0-9]+-*", "v[0-9]+.[0-9]+.[0-9]+-*"]

env:
  BUILD_TAG: ${{ contains(github.ref_name, '-') && 'development' || 'latest' }}

jobs:
  build-linux-x64:
    name: Build Client AppImage with Ubuntu.x64
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NPM
        working-directory: ./client
        run: npm install

      - name: Build AppImage
        working-directory: ./client
        run: npm run package

      - name: Upload AppImage to Github
        uses: actions/upload-artifact@v4
        with:
          name: "linux-deb-x64-${{ github.ref_name }}"
          path: ./client/release/build/*.AppImage
          if-no-files-found: error

      - name: Upload linux-raw to Github
        uses: actions/upload-artifact@v4
        with:
          name: "linux-portable-x64-${{ github.ref_name }}"
          path: ./client/release/build/linux-unpacked
          if-no-files-found: error

  build-windows-x64:
    name: Build Client App for Windows
    runs-on: windows-latest
    permissions:
      contents: read
      security-events: write
      actions: read 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NPM
        working-directory: ./client
        run: npm install

      - name: Build Client
        working-directory: ./client
        run: npm run package

      - name: Upload .exe to Github
        uses: actions/upload-artifact@v4
        with:
          name: "windows-exe-x64-${{ github.ref_name }}"
          path: ./client/release/build/*.exe
          if-no-files-found: error
          
      - name: Upload windows-raw to Github
        uses: actions/upload-artifact@v4
        with:
          name: "windows-portable-x64-${{ github.ref_name }}"
          path: ./client/release/build/win-unpacked
          if-no-files-found: error
  
  build-mac-arm64:
    name: Build Client App for macOS
    runs-on: macos-latest
    permissions:
      contents: read
      security-events: write
      actions: read 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NPM
        working-directory: ./client
        run: npm install

      - name: Build Client
        working-directory: ./client
        run: npm run make -- --targets=@electron-forge/maker-dmg

      - name: Upload .dmg to Github
        uses: actions/upload-artifact@v4
        with:
          name: "mac-dmg-arm64-${{ github.ref_name }}"
          path: ./client/release/build/*.dmg
          if-no-files-found: error
          
      - name: Upload mac-raw to Github
        uses: actions/upload-artifact@v4
        with:
          name: "mac-portable-arm64-${{ github.ref_name }}"
          path: ./client/release/build/mac-unpacked
          if-no-files-found: error
