# Builds and uploads artifacts for client

name: Build Client App

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-deb:
    name: Build Client App .deb with Ubuntu.x64
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NPM
        working-directory: ./client
        run: npm install

      - name: Build Client
        working-directory: ./client
        run: npm run make -- --targets=@electron-forge/maker-deb

      - name: Upload .deb to Github
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb-x64
          path: ./client/out/make/deb/x64/*.deb
          if-no-files-found: error

      - name: Upload linux-raw to Github
        uses: actions/upload-artifact@v4
        with:
          name: linux-raw-x64
          path: ./client/out/sync-stream-client-linux-x64
          if-no-files-found: error

  build-linux-rpm:
    name: Build Client App .rpm with Ubuntu.x64
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NPM
        working-directory: ./client
        run: npm install

      - name: Build Client
        working-directory: ./client
        run: npm run make -- --targets=@electron-forge/maker-rpm

      - name: Upload .rpm to Github
        uses: actions/upload-artifact@v4
        with:
          name: linux-rpm-x64
          path: ./client/out/make/rpm/x64/*.rpm
          if-no-files-found: error

  build-windows:
    name: Build Client App for Windows
    runs-on: windows-latest
    permissions:
      contents: read
      security-events: write
      actions: read 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NPM
        working-directory: ./client
        run: npm install

      - name: Build Client
        working-directory: ./client
        run: npm run make -- --targets=@electron-forge/maker-squirrel

      - name: Upload .exe to Github
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-x64
          path: ./client/out/make/squirrel.windows/x64/*.exe
          if-no-files-found: error
          
      - name: Upload linux-raw to Github
        uses: actions/upload-artifact@v4
        with:
          name: windows-raw-x64
          path: ./client/out/sync-stream-client-win32-x64
          if-no-files-found: error
