name: Build Server Docker Image

on:
  release:
    types: [published]
  
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: ghcr.io
          dockerfile: ${{path/to/Dockerfile}}
          username: ${secrets.USERNAME}
          password: ${{secrets.PASSWORD}}
          image_name: sync_stream
          push_git_tag: true