name: Build Server Docker Image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    paths:
      - server/**
      
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          context: ./server
          username: SyncStream-Org
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: ghcr.io
          image_name: sync-stream
