name: Build Server Docker Image

on:
  pull_request:
    branches:
      - main
    paths:
      - server/**
  push:
    branches:
      - main
    paths:
      - server/**
      
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          context: ./server
          push_image_and_stages: false
          image_name: sync_stream
