name: Build Server Docker Image

on:
  workflow_dispatch:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+-?[a-zA-Z0-9]+']
    branches: [main]
      
jobs:
  server:
    name: Build and Push Docker Container
    runs-on: ubuntu-latest
    permissions:
      write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          context: ./server
          username: SyncStream-Org
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: ghcr.io
          image_name: "sync-stream:${{ github.ref_name }}"
