# ESLint on pull request.

name: ESLint Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  client:
    name: ESLint Client Source
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        working-directory: ./client
        run: |
          npm install
          npm install @microsoft/eslint-formatter-sarif

      - name: Run ESLint on Client
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        working-directory: ./client
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --format @microsoft/eslint-formatter-sarif -o eslint-results.sarif src/
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./client/eslint-results.sarif
          wait-for-processing: true
  
  server:
      name: ESLint Server Source
      runs-on: ubuntu-latest
      permissions:
        contents: read
        security-events: write
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install ESLint
          working-directory: ./server
          run: |
            npm install
            npm install @microsoft/eslint-formatter-sarif

        - name: Run ESLint on Server
          working-directory: ./server
          env:
            SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
          run: npx eslint -c eslint.config.mjs --format @microsoft/eslint-formatter-sarif -o eslint-results.sarif src/
          continue-on-error: true

        - name: Upload analysis results to GitHub
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: ./server/eslint-results.sarif
            wait-for-processing: true
