# Lint Server Folder on push or pull request

name: ESLint Server

on:
  workflow_dispatch:
  push:
    paths:
      - server/**
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '38 20 * * 3'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        working-directory: ./server
        run: npm install

      - name: Run ESLint on Server
        working-directory: ./server
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint -c eslint.config.mjs --format @microsoft/eslint-formatter-sarif -o eslint-results.sarif src/
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./server/eslint-results.sarif
          wait-for-processing: true
