name: Testing Client with Jest

on:
  pull_request:
    paths:
      - client/**
    branches: [ "main" ]

jobs:
  Client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests on Client
        run: |
          cd client
          npm install 
          npm test
