name: Testing with Jest

on:
  pull_request:
    paths:
      - server/**
    branches: [ "main" ]


jobs:
  Client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests on Client
        run: |
          cd client
          npm install 
          npm test
  Server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests on Server
        run: |
          cd server
          npm install 
          npm test
