name: Run Jest Tests (Backend)

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.7.0'
          
      - name: Install dependencies (global)
        run: npm install
        
      - name: Install dependencies (backend)
        working-directory: backend
        run: npm install

      - name: Run Jest tests (backend)
        working-directory: backend
        env:
          CI_ON: true
        run: npm run test:ci

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: npm install

      - name: Run Jest tests (frontend)
        working-directory: frontend
        run: npx jest --ci